apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-app-github-0321
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-app-github-0321 
  name: go-app-github-0321
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-app-github-0321 
